apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: todoapp-health-check-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busyboxplus-curl
            image: radial/busyboxplus:curl
            resources:
              requests:
                memory: "32Mi"
                cpu: "25m"
              limits:
                memory: "64Mi"
                cpu: "50m"
            command: ["curl", "-s", "http://todoapp-service:8080/api/health"]
          restartPolicy: OnFailure