apiVersion: v1
kind: Service
metadata:
  name: todoapp-service # Ця назва має збігатися з тією, що використовується в DaemonSet та CronJob
  namespace: mateapp
spec:
  selector:
    app: todoapp # Ця мітка має відповідати міткам вашого Deployment
  ports:
    - protocol: TCP
      port: 8080 # Порт, на якому сервіс доступний в кластері
      targetPort: 8080 # Порт, на якому Django-додаток слухає всередині контейнера
  type: ClusterIP # Додаток доступний тільки всередині кластера